spring:
  h2:
    console:
      enabled: true
      path: /h2.console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true  
    properties:
      jakarta:
        persistence:
          validation:
            mode: none
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non-contextual-creation: true  
  sql:
    init:
      mode: never         
  datasource:
    url: jdbc:postgresql://localhost:5432/emp_mgmnt
    username: postgres  
    password: admin
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    cache: false           